import { useEffect, useState } from "react";
import Head from "next/head";
import { FloatingLabel, Form } from "react-bootstrap";
import useDiscordAuth from "../hooks/useDiscordAuth";
import { ImageData } from "@lilnouns/assets";

function SVG({ b64 }) {
  return (
    <img
      className="w-full rounded-lg"
      src={`data:image/svg+xml;base64,${b64}`}
    />
  );
}

export default function Home() {
  const [b64, setb64] = useState();
  const [head, setHead] = useState(1);
  const [nounBody, setNounBody] = useState(1);
  const [eyewear, setEyewear] = useState(1);
  const [accessory, setAccessory] = useState(1);
  const { authorization, onOpen } = useDiscordAuth("identify");

  const {
    images: { bodies, heads, accessories, glasses },
  } = ImageData;

  const bodyNames = bodies.map((body) => body.filename.slice(5));
  const headNames = heads.map((head) => head.filename.slice(5));
  const glassesNames = glasses.map((glasses) => glasses.filename.slice(8));
  const accessoryNames = accessories.map((accessory) =>
    accessory.filename.slice(10)
  );

  useEffect(() => {
    const _ = async () => {
      const res = await fetch("/api/getNoun", {
        method: "POST",
        body: JSON.stringify({
          background: 1,
          head: head,
          body: nounBody,
          glasses: eyewear,
          accessory: accessory,
        }),
      });
      const body = await res.json();
      setb64(body.response);

      // await fetch("/api/newNoun", {
      //   method: "POST",
      //   body: JSON.stringify({
      //     background: 1,
      //     head: head,
      //     body: nounBody,
      //     glasses: eyewear,
      //     accessory: accessory,
      //   }),
      // });
    };
    _();
  }, [head, nounBody, eyewear, accessory]);

  return (
    <div>
      <Head>
        <title>Noun Trait Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-screen-lg mx-auto">
        <button
          onClick={() => {
            onOpen();
          }}
        >
          discord
        </button>
        <h1 className="text-black text-3xl text-center">Lil Nouns Notifier</h1>
        <div className="grid grid-cols-3 gap-4">
          <div className="col-span-1 flex flex-col space-y-4">
            <FloatingLabel controlId="floatingSelect" label="Head">
              <Form.Select
                aria-label="Floating label select example"
                onChange={(e) => setHead(e.target.value)}
              >
                {headNames.map((name, idx) => (
                  <option key={idx} value={idx}>
                    {name}
                  </option>
                ))}
              </Form.Select>
            </FloatingLabel>

            <FloatingLabel controlId="floatingSelect" label="Body">
              <Form.Select
                aria-label="Floating label select example"
                onChange={(e) => setNounBody(e.target.value)}
              >
                {bodyNames.map((name, idx) => (
                  <option key={idx} value={idx}>
                    {name}
                  </option>
                ))}
              </Form.Select>
            </FloatingLabel>

            <FloatingLabel controlId="floatingSelect" label="Glasses">
              <Form.Select
                aria-label="Floating label select example"
                onChange={(e) => setEyewear(e.target.value)}
              >
                {glassesNames.map((name, idx) => (
                  <option key={idx} value={idx}>
                    {name}
                  </option>
                ))}
              </Form.Select>
            </FloatingLabel>

            <FloatingLabel controlId="floatingSelect" label="Accessories">
              <Form.Select
                aria-label="Floating label select example"
                onChange={(e) => setAccessory(e.target.value)}
              >
                {accessoryNames.map((name, idx) => (
                  <option key={idx} value={idx}>
                    {name}
                  </option>
                ))}
              </Form.Select>
            </FloatingLabel>
            <a
              href={`https://discord.com/api/oauth2/authorize?&client_id=977779948590886952&permissions=268435456&scope=bot`}
              className="bg-red-500 rounded text-white py-2"
            >
              Auth Bot
            </a>
          </div>
          <div className="col-span-2">
            <SVG b64={b64} />
          </div>
        </div>
      </main>
    </div>
  );
}
